dineblackapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import *

app_name = "dineblackapp"

urlpatterns = [
  path('restaurants/', restaurant_list, name='restaurants'),
  path('logout/', logout_user, name='logout'),
  path('register/', register_user, name="register"),
  path('', restaurant_list, name='home'),
  path('checkins', check_in_list, name='checkins'),
  path('favorites', favorite_list, name='favorites'),
  path('accounts/', include('django.contrib.auth.urls')),
  path('favorites/<int:favoriterestaurant_id>/', favorite_delete, name='favorite'),
  path('checkins/<int:restaurantdishreview_id>/', checkin_change, name='checkin'),
  path('checkins/<int:restaurantdishreview_id>/form/', checkin_edit_form, name='checkin_edit_form'),
  path('restaurants/<int:restaurant_id>/', restaurant_details, name='restaurant'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dineproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from dineblackapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dineblackapp.urls')),
]

dineblackapp/models.py
from django.db import models

# Create your models here.

dineblackapp/models/diner.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse

class Diner(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=75)
    phone_number = models.CharField(max_length=10)

    class Meta:
        verbose_name = ("diner")
        verbose_name_plural = ("diners")

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse("diner_detail", kwargs={"pk": self.pk})

    @receiver(post_save, sender=User)
    def create_diner(sender, instance, created, **kwargs):
        if created:
            Diner.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_diner(sender, instance, **kwargs):
        instance.diner.save()
    

dineblackapp/models/favorite_restaurant.py
from .restaurant import Restaurant
from .diner import Diner
from django.db import models
from django import forms

class FavoriteRestaurant(models.Model):

    restaurant = models.ForeignKey(Restaurant, related_name=("restaurant"), on_delete=models.DO_NOTHING, null=True, blank=True)
    diner = models.ForeignKey(Diner, on_delete=models.DO_NOTHING, null=True, blank=True)

    class Meta:
        verbose_name = ("favorite_restaurant")
        verbose_name_plural = ("favorite_restaurants")
        unique_together = ('restaurant', 'diner')

    def __str__(self):
        return self.restaurant_id
    
    def clean_restaurant_name(self):
        restaurant_name = self.cleaned_data.get('restaurant')

        
   

dineblackapp/models/restaurant.py
from django.db import models
from django.urls import reverse

class Restaurant(models.Model):

    name = models.CharField(max_length=50)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    phone_number = models.CharField(max_length=15)
    latitude = models.DecimalField(max_digits=10, decimal_places=1)
    longitude = models.DecimalField(max_digits=10, decimal_places=1)
    image = models.CharField(max_length=300, null=True)
    google_maps_link = models.CharField(max_length=300, null=True)
    
    
    class Meta:
        verbose_name = ("restaurant")
        verbose_name_plural = ("restaurants")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Restaurant_detail", kwargs={"pk": self.pk})
    
        
            

dineblackapp/models/restaurant_dish_review.py
from .restaurant import Restaurant
from .diner import Diner
from django.db import models
from django.urls import reverse


class RestaurantDishReview(models.Model):

    dish_rating_number = models.IntegerField(null=True)
    dish_name = models.CharField(max_length=25)
    dish_img = models.CharField(max_length=25)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.DO_NOTHING, null=True, blank=True)
    diner = models.ForeignKey(Diner, on_delete=models.DO_NOTHING, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=100, null=True, blank=True)

dineblackapp/models/restaurant_rating.py
from .restaurant import Restaurant
from .diner import Diner
from django.db import models
from django.urls import reverse

class RestaurantRating(models.Model):

    restaurant_rating_number = models.DecimalField(max_digits=10, decimal_places=1, null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.DO_NOTHING, null=True, blank=True)
    diner = models.ForeignKey(Diner, on_delete=models.DO_NOTHING, null=True, blank=True)

    class Meta:
        verbose_name = ("restaurant_rating")
        verbose_name_plural = ("restaurant_ratings")


    def __str__(self):
        return self.rating_number

dineblackapp/views.py
from django.shortcuts import render

# Create your views here.

dineblackapp/views/connection.py
class Connection:
    db_path = "/Users/stephencastaneda/workspace/python/dine-black/dineproject/db.sqlite3"
    

dineblackapp/templates/checkins/edit_form.html
{% extends 'shared/base.html' %}

{% block content %}
  <body>
    <h1>Edit Check In</h1>
      <form action="{% url 'dineblackapp:checkin' dish_review.id %}" method="post">
      {% csrf_token %}
        <fieldset>
            <label for="dish_name">Dish Name: </label>
            <input id="dish_name" type="text" name="dish_name" value="{{ dish_review.dish_name }}">
        </fieldset>
         <fieldset>
          <label for="dish_image">Dish Image: </label>
          <input type="button" id="upload_widget" class="cloudinary_button" value="Upload image"></button>
          <input id="dish_image" type="hidden" value="" name="dish_image">
        </fieldset>
        <fieldset>
            <label for="description">Description: </label>
            <input id="description" type="text" name="description" value="{{ dish_review.description }}">
        </fieldset>
        <fieldset>
            <label for="dish_rating_number">Dish Rating Number: </label>
            <input id="dish_rating_number" type="number" min="1" max="5" name="dish_rating_number" value="{{ dish_review.dish_rating_number }}">
        </fieldset>
        <fieldset>
            <label for="restaurant">Restaurant: </label>
            <select id="restaurant" type="text" name="restaurant">
                {% for restaurant in all_restaurants %}
                <option {% if restaurant.id == dish_review.restaurant_id %}selected{% endif %} value="{{ dish_review.restaurant_id }}">
                    {{ restaurant.name }}</option>
                {% endfor %}
            </select>
        </fieldset>
         <input type="hidden" name="actual_method" value="PUT">
          <input type="submit" value="Update" />    
  </body>
{% endblock content %}

dineblackapp/templates/checkins/list.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="accordion pt-3" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn add_checkin_btn" style="border:none; background:none" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         <i class="fas fa-plus-square"></i> Check In
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
    <form style="color:black" class="check_in_edit_form" action="{% url 'dineblackapp:checkins' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="dish_name">Dish Name: </label>
          <input id="dish_name" type="text" name="dish_name">
      </fieldset>
      <fieldset>
          <label for="dish_image">Dish Image: </label>
          <input type="button" id="upload_widget" class="cloudinary_button" value="Upload image"></button>
          <input id="dish_image" type="hidden" value="" name="dish_image">
      </fieldset>
      <fieldset>
          <label for="description">Description: </label>
          <input id="description" type="text" name="description" maxlength="65">
      </fieldset>
      <fieldset>
          <label for="dish_rating_number">Dish Rating Number: </label>
          <input id="dish_rating_number" type="number" min="1" max="5" name="dish_rating_number">
      </fieldset>
      <fieldset>
          <label for="restaurant">Restaurant: </label>
          <select id="restaurant" type="text" name="restaurant">
                {% for restaurant in restaurants %}
                    <option value="{{ restaurant.id }}">{{ restaurant.name }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Check-In" />
    </form>
      </div>
    </div>
  </div>

  <body>

<h3 class="check_in_user_name_title">{{ user.first_name }}'s Check-Ins</h3>
 <div class="d-flex flex-wrap">
    {% for user_check_in in user_check_ins %}
    <div class="card m-3 p-3" style="width: 18rem;">
      <img class="card-img-top rounded"  width="240px" height="200px" src="{{ user_check_in.dish_img }}" alt="Card image cap">
        <div class="card-body">
          <p class="card-text text-center">{{ user_check_in.dish_rating_number }}</p>
          <h5 class="card-title">{{ user_check_in.restaurant.name }}</h5>
          <p class="card-text">{{ user_check_in.dish_name }}</p>
          <p class="card-text description-text">"{{ user_check_in.description }}"</p>
          <section id="checkin-actions" style="display:flex;justify-content:space-between;">
          <form action="{% url 'dineblackapp:checkin' user_check_in.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
      <button style="border:none; background:none" class="btn checkin_edit_font_awesome"><i class="fas fa-trash-alt"></i></button>
          </form>
          <form action="{% url 'dineblackapp:checkin_edit_form' user_check_in.id %}" method="GET">
            {% csrf_token %}
      <button style="border:none; background:none" class="btn checkin_delete_font_awesome"><i class="fas fa-pencil-alt"></i></button>
          </form>
      </section>
    </div>
  </div>
{% endfor %}

{% endblock content %}

dineblackapp/templates/favorite_restaurants/list.html
{% extends 'shared/base.html' %}

{% block content %}

<div class="accordion pt-3" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn add_checkin_btn" style="border:none; background:none" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         <i class="fas fa-plus-square"></i> Favorite Restaurant
        </button>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
    <form class="add_favorite_form" style="color:black" action="{% url 'dineblackapp:favorites' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="restaurant">Restaurant: </label>
          <select id="restaurant" type="text" name="restaurant">
                {% for restaurant in restaurants %}
                    <option value="{{ restaurant.id }}">{{ restaurant.name }}</option>
                {% endfor %}
          </select>
      </fieldset>
      <input type="submit" value="Add-Favorite" />
      </form>
      </div>
    </div>
  </div>
    
<h3 class="user_favorite_title">My Favorites</h3>
     
  <div class="list-group favorite_restaurant_list">
    {% for user_favorite in user_favorites %}
    <a target="_blank" href="{{ user_favorite.restaurant.google_maps_link }}" class="list-group-item list-group-item-action favorite_restaurant_name fav_restaurant_list">{{ user_favorite.restaurant.name }}
      <div class="restaurant_delete_form">
        <section id="favorite-actions" class="favorite_restaurant_delete">
          <form action="{% url 'dineblackapp:favorite' user_favorite.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button style="border:none; background:none" class="btn favorite_restaurant_delete_font_awesome"><i class="fas fa-trash-alt"></i></button>
          </form>
        </section> 
      </div>
    </a>
  </div>
        
    {% endfor %}
    
{% endblock content %}

dineblackapp/templates/restaurants/detail.html
{% extends 'shared/base.html' %}

{% block content %}

<div class="restaurant_detail_info">
    <h2 class="restaurant_detail_title">{{ restaurant.name }}</h2>
    <h3> {{ restaurant.address }}</h3>
    <div>Phone Number: {{ restaurant.phone_number }}</div>
</div>
  <h3 class="restaurant_detail_checkin_title">{{ restaurant.name }} Check-Ins</h3>


    <div class="d-flex flex-wrap">
        {% for checkin in checkins %}
      <div class="card m-3 p-3" style="width: 18rem;">
        <img class="card-img-top rounded"  width="240px" height="200px" src="{{ checkin.dish_img }}" alt="Card image cap">
          <div class="card-body">
          <p class="card-text text-center">{{ checkin.dish_rating_number }}</p>
            <h5 class="card-title">{{ checkin.dish_name }}</h5>
            <p class="card-text">{{ checkin.diner.user.first_name }} {{ checkin.diner.user.last_name }}</p>
            <p class="card-text description-text"> "{{ checkin.description }}" </p>
          </div>
      </div>        
{% endfor %}
    </div>

  {% endblock content %}

dineblackapp/templates/restaurants/list.html
{% extends 'shared/base.html' %}

{% block content %}

    <div class="d-flex flex-wrap">
      {% for restaurant in all_restaurants %}
      <div class="card m-3 p-3 {% if restaurant.restaurantdishreview_set.all.count > 0 %} checkedin_restaurants {% endif %}" style="width: 18rem;">
        <img class="card-img-top rounded" width="240px" height="200px" src="{{ restaurant.image }}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ restaurant.name }}</h5>
          <p class="card-text">{{ restaurant.address }}</p>
            <button class="btn"><a  href="{% url 'dineblackapp:restaurant' restaurant.id %}"> Details </a></button>
        </div>
         <a class="btn" href="{{ restaurant.google_maps_link }}" target="_blank"><i class="fas fa-route"></i></a></button>
      </div>
    {% endfor %}
    </div>

{% endblock content %}

dineblackapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Dine.Black.</title>
    
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
      <link rel="stylesheet" href='../../static/styles/base.css'>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Rubik&display=swap" rel="stylesheet">
    <!-- Font Awesome JS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

    {% comment %} <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script> {% endcomment %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Dine.Black.</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dineblackapp:restaurants' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dineblackapp:favorites' %}">Favorite Restaurants</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dineblackapp:checkins' %}">CheckIn</a>
      </li>
      
      {% if user.is_authenticated %}

      <li class="nav-item mr-sm-2">
        <a class="nav-link" href="{% url 'dineblackapp:logout' %}">Logout</a>
      </li>
      {% endif %}

      {% if not user.is_authenticated %}
      <li class="nav-item mr-sm-2">
          <a class="nav-link" href="{% url 'dineblackapp:login' %}">Login</a>      
      </li>
      {% endif %}
      <li class="nav-item mr-sm-2">
        <a class="nav-link" href="{% url 'dineblackapp:register' %}">Register</a>
      </li>

</ul>
  </div>
</nav>


  





     <main class="main-content">{% block content %} {% endblock %}</main>
    

    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>

    <script type="text/javascript">  
    var myWidget = cloudinary.createUploadWidget({
    cloudName: 'dbjxqdddk', 
    uploadPreset: 'img_upload'}, (error, result) => { 
        if (!error && result && result.event === "success") { 
            document.getElementById('dish_image').value = result.info.secure_url
        }
    }
    )

    document.getElementById("upload_widget").addEventListener("click", function(){
    myWidget.open();
    }, false);

    </script>
</body>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

   
</body>

</html>